name: pixel_flix
description: "E-Commerce Mobile Application"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env

    - ./lib/images/
    - ./lib/images/register/
    - ./lib/images/splash/
    - ./lib/images/home/

    - ./lib/images/register/providers/
    - ./lib/images/register/avatars/
    - ./lib/images/register/modal/
